services:
  api:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    container_name: user_jwt_api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/api
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: user_jwt_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user_jwt_redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: