# 開発用のベースイメージ
FROM golang:1.23.2

# Air のインストール
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install github.com/swaggo/swag/cmd/swag@latest && \
    go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

# 作業ディレクトリ
WORKDIR /api

# モジュールファイルをコピーして依存関係をインストール
COPY go.mod go.sum ./
RUN go mod download

# Swagger UI ライブラリのインストール
RUN go get -u github.com/swaggo/gin-swagger && \
    go get -u github.com/swaggo/files

# # ソースコードをコピー
COPY . .

# # Air の設定ファイルをコピー
COPY .air.toml /api

# Air を使用してアプリケーションを実行
CMD ["air"]