# 開発用のベースイメージ
FROM golang:1.23.2

# Air のインストール
RUN go install github.com/cosmtrek/air@v1.40.4

# 作業ディレクトリ
WORKDIR /app

# モジュールファイルをコピーして依存関係をインストール
COPY go.mod go.sum ./
RUN go mod download

# # ソースコードをコピー
COPY . .

# # Air の設定ファイルをコピー
COPY .air.toml /app

# Air を使用してアプリケーションを実行
CMD ["air"]