openapi: 3.0.0
info:
  title: User JWT API
  version: 1.0.0
paths:
  /auth/sign-out:
    post:
      summary: Sign out
      description: Logs out the authenticated user
      tags:
        - auth
      responses:
        '200':
          description: Successfully signed out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully signed out"
        '401':
          description: Unauthorized